// Hand-written keyword index for the `recommend_components_for_prd` MCP tool.
//
// Each kb-ui component has 5–12 keywords (single words and 2–3 word phrases).
// The score function (see ./tools/recommend-components-for-prd.ts) walks this
// map and matches against the tokenized PRD:
//   +1  per single-token keyword match
//   +3  per bigram keyword match
//   +5  per 3-word phrase verbatim in the PRD
//   +2  if the component name itself appears in the PRD
//
// Coverage rule: every one of the 36 components currently exported by
// @test-kb-ui/kb-ui must have an entry — see test fixtures and the smoke output
// for the live recommendation surface.

export const componentKeywords: Record<string, string[]> = {
  /* ── shell ───────────────────────────────────────────────── */
  AppShell: [
    'layout',
    'app shell',
    'page wrapper',
    'application frame',
    'shell',
    'standard layout',
    'main layout',
    'app layout',
  ],
  KBBreadcrumbBar: [
    'breadcrumb',
    'breadcrumb bar',
    'navigation bar',
    'page header bar',
    'publish action',
    'top bar',
    'editor toolbar',
    'header bar',
  ],

  /* ── nav ─────────────────────────────────────────────────── */
  SideNavRail: [
    'rail',
    'icon nav',
    'left navigation',
    'side nav',
    'side navigation',
    'app rail',
    'vertical nav',
    'navigation rail',
    'side rail',
  ],
  FileExplorerNav: [
    'file explorer',
    'tree nav',
    'folder tree',
    'category tree',
    'sidebar tree',
    'expandable nav',
    'left sidebar',
    'navigation tree',
    'analytics sub nav',
    'sub nav',
  ],

  /* ── primitives ──────────────────────────────────────────── */
  Avatar: [
    'avatar',
    'user image',
    'profile picture',
    'user circle',
    'profile photo',
    'user photo',
  ],
  Badge: [
    'badge',
    'status',
    'label',
    'tag',
    'pill',
    'status tag',
    'status badge',
  ],
  Breadcrumb: [
    'breadcrumb',
    'crumb trail',
    'path nav',
    'navigation path',
    'trail',
  ],
  Button: [
    'button',
    'cta',
    'action',
    'primary action',
    'click',
    'submit',
    'save button',
    'publish button',
  ],
  Card: [
    'card',
    'panel',
    'container',
    'box',
    'tile',
    'group',
    'section card',
  ],
  Divider: [
    'divider',
    'separator',
    'rule',
    'horizontal line',
    'vertical line',
  ],
  Dropdown: [
    'dropdown',
    'select',
    'menu',
    'picker',
    'options menu',
    'select menu',
    'combobox',
  ],
  TextInput: [
    'input',
    'text field',
    'form field',
    'text box',
    'enter text',
    'search box',
    'text input',
  ],

  /* ── content ─────────────────────────────────────────────── */
  AICard: [
    'ai card',
    'ai panel',
    'ai callout',
    'ai feature card',
    'ai banner',
  ],
  AIConversationLogEntry: [
    'conversation log',
    'ai chat log',
    'conversation entry',
    'log entry',
    'chat entry',
  ],
  AIConversationLogsCard: [
    'conversation logs',
    'ai chat logs',
    'logs card',
    'chat history',
    'conversation history',
  ],
  AIGapSuggestionCard: [
    'ai suggestion',
    'ai gap',
    'inline suggestion',
    'review suggestion',
    'addition replace removal',
    'accept dismiss',
    'gap suggestion',
  ],
  AISuggestionsCard: [
    'ai suggestions list',
    'review queue',
    'suggestion summary',
    'pre-review',
    'ai suggestions',
    'suggestions card',
  ],
  AnalyticsAreaChart: [
    'area chart',
    'time series',
    'trend',
    'over time',
    'area graph',
    'line chart',
    'trend chart',
  ],
  AnalyticsChartCard: [
    'chart card',
    'chart container',
    'chart wrapper',
    'chart panel',
    'analytics card',
  ],
  AnalyticsDonutChart: [
    'donut',
    'pie',
    'donut chart',
    'pie chart',
    'distribution chart',
    'breakdown chart',
    'distribution',
  ],
  ArticleBody: [
    'article body',
    'article content',
    'rendered article',
    'read mode',
    'article display',
    'article view',
    'reading view',
  ],
  ArticleSettingsPanel: [
    'article settings',
    'metadata',
    'article properties',
    'side panel',
    'publish settings',
    'settings panel',
    'article metadata',
  ],
  ContentEditor: [
    'editor',
    'rich text',
    'wysiwyg',
    'tiptap',
    'content editor',
    'write article',
    'compose',
    'article editor',
    'rich text editor',
  ],
  DataTable: [
    'table',
    'data table',
    'list view',
    'rows',
    'tabular',
    'spreadsheet',
    'grid',
    'list of articles',
    'ranked list',
  ],
  DateRangePill: [
    'date range',
    'time picker',
    'date filter',
    'last 30 days',
    'date pill',
    'last 7 days',
    'date selector',
    'time range',
  ],
  HelpfulnessTag: [
    'helpfulness',
    'thumbs',
    'feedback tag',
    'helpful unhelpful',
    'helpful tag',
    'feedback indicator',
  ],
  NavArrow: [
    'nav arrow',
    'arrow icon',
    'chevron',
    'expand arrow',
    'collapse arrow',
  ],
  PageHeader: [
    'page header',
    'page title',
    'title bar',
    'section title',
    'new article cta',
    'header with action',
  ],
  SlashCommandMenu: [
    'slash menu',
    'command menu',
    'slash command',
    'quick actions menu',
    'command palette',
    'insert menu',
  ],
  StatCard: [
    'stat',
    'metric',
    'kpi',
    'number card',
    'stat card',
    'metric card',
  ],
  StatCardGrid: [
    'stat grid',
    'metrics row',
    'kpi grid',
    'dashboard stats',
    'stat row',
    'metric grid',
    'totals at the top',
  ],
  SuggestionBlock: [
    'inline suggestion',
    'highlight block',
    'suggestion wash',
    'addition removal block',
    'inline diff',
  ],
  SuggestionCard: [
    'suggestion',
    'recommendation card',
    'hub card',
    'suggestion tile',
    'recommendation',
  ],

  /* ── overlays ────────────────────────────────────────────── */
  SourcesSideSheet: [
    'sources',
    'side sheet',
    'drawer',
    'sources drawer',
    'overlay sheet',
    'sources panel',
    'side drawer',
  ],

  /* ── brand ───────────────────────────────────────────────── */
  AiIcon: [
    'ai icon',
    'sparkle',
    'gradient ai glyph',
    'ai sparkle',
    'ai indicator',
  ],
  CompanyLogo: [
    'logo',
    'brand',
    'company logo',
    'brand mark',
    'wordmark',
  ],
};
